version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: project_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_BACKEND_URL=/api/persons/

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: project_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    container_name: project_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
