jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SECRETKEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: Osa4/Bloglist
        run: npm install

      - name: Run ESLint
        working-directory: Osa4/Bloglist
        run: npm run lint

      - name: Run Tests
        working-directory: Osa4/Bloglist
        run: npm test
